# Generated by Django 4.0.2 on 2022-02-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruduser',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='age',
        ),
        migrations.AddField(
            model_name='cruduser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='lastname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
